---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/mysite.conf
    mode: '0644'

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/mysite.conf
    dest: /etc/nginx/sites-enabled/mysite.conf
    state: link
    force: yes

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded

