services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    hostname: server
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    networks:
      - mongodb_network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb_network

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network